### ISSUE TITLE
how can I test it with curl?

### ISSUE THREAD

**Issue by JDJoe** [Robswc/tradingview-webhooks-bot#10]
I followed the instructions from https://github.com/Robswc/tradingview-webhooks-bot/issues/8 
Made the changes to the script and started it. Runs OK, seems to listen port 5000 
How can I test it from a outside to make sure it actually works OK. (I am not a developer so...  ;)

**Comment by Robswc** [comment]
hey,
Have you set up the tradingview alerts?  That should be the best way to test :)

**Comment by JDJoe** [comment]
It seems my "problem" is actually with my VPS I was planning to use. 
I started the script as instructed but it's not accessible form outside. 

It sound like I have to make it work with Apache:
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-flask-application-on-an-ubuntu-vps

**Comment by JDJoe** [comment]
So, I got the test flask app running but that's about it :) 
I ran out of ideas what to modify to get your app running with Apache

**Comment by JDJoe** [comment]
`curl -H "Content-Type: application/json" -X POST -d '{"type": "limit", "side": "buy", "amount": "1000", "symbol": "XBTUSD", "price": "30", "key": "youneedyourkeyhere"}' http://127.0.0.1:5000/webhook`

Of course, you change the URL to what ever you have there.

**Comment by Robswc** [comment]
awesome, thanks for providing the solution for future users!
