### ISSUE TITLE
Add log to a file

### ISSUE THREAD

**Issue by JDJoe** [Robswc/tradingview-webhooks-bot#12]
When running it via apache, there is no way to see how exchange replies or if something happens. So, some kind log file is needed.

**Comment by Robswc** [comment]
Added in 2020.1 branch.  Will eventually merge into main branch, 2020.1 should be considered a beta for the time being.

https://github.com/Robswc/tradingview-webhooks-bot/tree/2020.1

Logging is turned on by default, goes to a csv file.

**Comment by JDJoe** [comment]
BTW, how do I use it?

**Comment by Robswc** [comment]
It should log any incoming POST requests and orders to the logs/log.csv file.

It can also display them via the GUI, which is the app.py file.  Will think of a better name eventually lol
