### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by roboluc** [Robswc/tradingview-webhooks-bot#2]
Is there any documentation for this project?

**Comment by roboluc** [comment]
Oh thank you very much I would love a quick start quide!

**Comment by Robswc** [comment]
hey! not sure if you still need it but I made this, its really crude but hopefully it gets you started!

https://github.com/Robswc/tradingview-webhooks-bot/wiki/Quick-Start-Guide

**Comment by roboluc** [comment]
Thank you for the documentation but I figured it out myself (;
I have the script running on a server and it is working great! Thank you very much for sharing this code!

**Comment by Robswc** [comment]
awesome! glad its working for you!
