### ISSUE TITLE
How to add Oanda API

### ISSUE THREAD

**Issue by bkcollection** [robswc/tradingview-webhooks-bot#20]
Thanks for your good work.
I would like to know how can I add Oanda API by using your Python module.
It will be good if we can add other brokers.

Thanks

**Comment by Robswc** [comment]
hey, sorry for the delay.

Have you figured this out? @bkcollection if not, it should be possible.  You can connect with any API in theory using the requests library for python.

**Comment by david03kimo** [comment]
this is my concern, too.
