### ISSUE TITLE
Warning: Python 3.7 was not found on your system…

### ISSUE THREAD

**Issue by Fredrik81** [robswc/tradingview-webhooks-bot#23]
Fresh install of Ubuntu 20.04 that has python 3.8 gives this error:
```
pipenv install
Warning: Python 3.7 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python

```
Possible that you can test and fix?

I changed Pipfile to this and it was at least installing:
```
[requires]
python_version = "3.8"
```

**Comment by Robswc** [comment]
Hey! I'm not sure to be honest, as that would be more of a python problem.  It might not have registered correctly?  Have you found the solution in the mean time?  Pipenv is not *technically* required, can you verify if python itself is working fine?

**Comment by alperoguz** [comment]
Hi,
Ubuntu 20.04 comes with Python 3.8.5. I replaced python_version with "3.8" like @Fredrik81 mentioned above and webhook works fine so far. You can see output below:

```
$ python webhook-bot.py
 * Serving Flask app "webhook-bot" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Dec/2020 06:38:28] "GET / HTTP/1.0" 200 -
```

I can get answer when query a browser or curl:
```
$ curl localhost:5000
online
```
I haven't test API functionality yet.

**Comment by robswc** [comment]
> Hi,
> Ubuntu 20.04 comes with Python 3.8.5. I replaced python_version with "3.8" like @Fredrik81 mentioned above and webhook works fine so far. You can see output below:
> 
> ```
> $ python webhook-bot.py
>  * Serving Flask app "webhook-bot" (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
> 127.0.0.1 - - [02/Dec/2020 06:38:28] "GET / HTTP/1.0" 200 -
> ```
> 
> I can get answer when query a browser or curl:
> 
> ```
> $ curl localhost:5000
> online
> ```
> 
> I haven't test API functionality yet.

Looks like the solution!
