### ISSUE TITLE
Use % of available funds

### ISSUE THREAD

**Issue by GrandChamp21** [robswc/tradingview-webhooks-bot#29]
Is it possible to place an order using the % of available funds? 

Thanks for the great work!

**Comment by alperoguz** [comment]
up

**Comment by robswc** [comment]
> Is it possible to place an order using the % of available funds?
> 
> Thanks for the great work!

Sorry for the late reply.

Its technically possible to do anything, as long as you can do it in python ;) 

You would have to grab the % of user funds from your broker's API.
