### ISSUE TITLE
Method Not Allowed flask error 405

### ISSUE THREAD

**Issue by roboluc** [Robswc/tradingview-webhooks-bot#3]
Hi I get "Method Not Allowed flask error 405" when I try to run your script any solution?

**Comment by roboluc** [comment]
Nevermind I fixed it it's working now!

**Comment by alsopgroup** [comment]
how did you resolve it

**Comment by roboluc** [comment]
You first need to get Ngrok up and running after that you can send the tradingview alerts to your localhost flask server. Check wiki for details [](https://github.com/Robswc/tradingview-webhooks-bot/wiki/Quick-Start-Guide). But you can also buy a domain name and forward it to your own flask server then you don't need Ngrok.

**Comment by alsopgroup** [comment]
Ya I did have it running.  It looks like I needed to use /webhook on my ngrok link to get it to work
