### ISSUE TITLE
COMPLETE INSTRUCTIONS ON SET UP 

### ISSUE THREAD

**Issue by mrdamfur** [robswc/tradingview-webhooks-bot#32]
Remove this waste peoples fucking time .. if yo udo not have clear instructions take this down ..

**Comment by mrdamfur** [comment]
stop wasting people time

**Comment by timquinn** [comment]
I got mine setup in like 8 seconds.  What's the problem?

**Comment by robswc** [comment]
> stop wasting people time

Look, this is **Free** software.  I spent hours, days probably developing it.  Would also have to spend hours creating content for the wiki.  Lots of people have no issue with setting it up and those that do, simply ask on twitter or something.

If you want to volunteer to contribute to the wiki or setup instructions, please lmk.

**Comment by ApopheniaPays** [comment]
Without wanting to be rude like OP, I do agree in some ways. I find the steps required to get this working with my broker kind of opaque. The quickstart will get it installed but I'm not sure what to do beyond that. I'm hoping to get it going with TDA, which has means handling not just the trading API but OAuth. And if someone can get me at least far enough in that direction to get it to where I can get to work adapting some of the TDA OAuth and API wrappers I've found elsewhere on Github, if I can get the whole thing working I'd be happy to share the results back to the repo for anyone else's benefit.

**Comment by robswc** [comment]
> Without wanting to be rude like OP, I do agree in some ways. I find the steps required to get this working with my broker kind of opaque. The quickstart will get it installed but I'm not sure what to do beyond that. I'm hoping to get it going with TDA, which has means handling not just the trading API but OAuth. And if someone can get me at least far enough in that direction to get it to where I can get to work adapting some of the TDA OAuth and API wrappers I've found elsewhere on Github, if I can get the whole thing working I'd be happy to share the results back to the repo for anyone else's benefit.

This makes sense.

So, the "bot" is kinda misnomer, as it doesn't "execute" trades for you.  Its more or less a bridge between TV and your computer/server.  I tried to write in a way that basically limited the scope to "do stuff when alert comes in."

In this specific scenario, I would use tda-api and let that handle the OAuth headache lol.  Once you get tda-api working, making trades and what not, you could move it into tradingview-webhooks-bot.

There is a 2021.1 branch, that operates almost completely different from the current version.  I plan to get that supported soon, if you want to take a stab at it rn, feel free.  The documentation is a bit of a mess, as it was more or less me trying to just cover everything this time around lol.
