### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by alsopgroup** [Robswc/tradingview-webhooks-bot#5]
I keep getting this on post messages
HTTP Requests
-------------

POST /                         405 METHOD NOT ALLOWED

**Comment by alias-noa** [comment]
This is what i'm getting too.  So far i'm thinking it might be something to do with Windows 10.  I need to try it on Ubuntu to verify this.

**Comment by alias-noa** [comment]
Okay I finally got through.  It was the /webhook part in the webhook-bot.py file.  On this line:

@app.route('/webhook', methods=['POST'])

I didn't realize you have to put /webhook after your ngrok address in the tradingview webhook box.

**Comment by Robswc** [comment]
@alias-noa 's answer is correct.  Will update the guide to include this.

**Comment by alperoguz** [comment]
Hello @robswc 
I am not using ngrok. Do I still need to use /webrook in TV?

sorry for flooding with couple of questions.
