### ISSUE TITLE
Conflict Jinga vs flask in requirements

### ISSUE THREAD

**Issue by dorienh** [robswc/tradingview-webhooks-bot#60]
Just tried installing from repo but there is a conflict with dependencies: 

```
The conflict is caused by:
    The user requested Jinja2==3.1.1
    flask 2.3.2 depends on Jinja2>=3.1.2
```

updating one dependency led to another conflict. Finally, this set worked, but I'm hoping nothing broke... 

```
click==8.1.3
colorama==0.4.5
Flask==2.3.2
gunicorn==20.1.0
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.1
shellingham==1.4.0
typer==0.4.0
typer-cli==0.0.13
Werkzeug==2.3.3
```

Update: yes, when I try to run, I notice the following error: 

`cannot import name 'get_terminal_size' from 'click.termui'`

**Comment by robswc** [comment]
@dorienh I've gone and upgraded the dependencies, it should be working now!

Let me know if there's any issues!

https://github.com/robswc/tradingview-webhooks-bot/pull/63
