### ISSUE TITLE
Can't find `pinescript_test.txt` in the repo

### ISSUE THREAD

**Issue by tomav** [Robswc/tradingview-webhooks-bot#9]
This file is mentioned in the wiki but can't find it anywhere.

**Comment by Robswc** [comment]
you're right! Uploaded it now, here:

https://github.com/Robswc/tradingview-webhooks-bot/blob/master/tradingview-webhooks-bot/examples/pinescript_test.txt

when creating the alert, just set it to go off every minute 👍
